export const DEFAULT_SETTINGS = {
  enabled: true,
  cartPosition: "bottom-right",
  backgroundColor: "#000000",
  iconColor: "#ffffff",
  buttonRadius: 50,
  width: 80,
  height: 80,
  quantityBackgroundColor: "#ff0000",
  quantityTextColor: "#ffffff",
  quantityBadgeWidth: 24,
  quantityBadgeHeight: 24,
  quantityBadgeRadius: 50,
  showQuantityBadge: true,
  selectedIcon: "cart",
  uploadedIconData: null,
  uploadedIconType: null,
  customIconWidth: 50,
  customIconHeight: 50,
  quantityBadgePosition: "top-right",
  priceBackgroundColor: "transparent",
  deviceVisibility: "all",
  enableHoverAnimation: true,
  animationType: "bounce",
  showPricing: true,
  pricingTextColor: "#ffffff",
  pricingFontSize: 12,
  pricingFontWeight: "500",
  customCSS: "",
  structuredTopSectionBgColor: "#6b7280",
  structuredBottomSectionBgColor: "#f9fafb",
  structuredItemsTextColor: "#fbbf24",
  structuredPriceTextColor: "#374151",
  structuredCurrencySymbol: "৳",
};

export const OPTIONS = {
  position: [
    { label: "Bottom Right", value: "bottom-right" },
    { label: "Bottom Left", value: "bottom-left" },
    { label: "Center Right", value: "center-right" },
    { label: "Center Left", value: "center-left" },
    { label: "Top Right", value: "top-right" },
    { label: "Top Left", value: "top-left" },
  ],
  icon: [
    { label: "Shopping Cart", value: "cart" },
    { label: "Shopping Bag", value: "bag" },
    { label: "Basket", value: "basket" },
    { label: "Custom", value: "custom" },
  ],
  device: [
    { label: "All Devices", value: "all" },
    { label: "Mobile Only", value: "mobile-only" },
    { label: "Desktop Only", value: "desktop-only" },
  ],
  animation: [
    { label: "Bounce", value: "bounce" },
    { label: "Pulse", value: "pulse" },
    { label: "Shake", value: "shake" },
    { label: "None", value: "none" },
  ],
  layout: [
    { label: "Normal Layout", value: "normal" },
    { label: "Structured Layout", value: "structured" },
  ],
  badgePosition: [
    { label: "Top Right Corner", value: "top-right" },
    { label: "Top Left Corner", value: "top-left" },
    { label: "Bottom Right Corner", value: "bottom-right" },
    { label: "Bottom Left Corner", value: "bottom-left" },
  ],
  fontWeight: [
    { label: "Normal", value: "400" },
    { label: "Medium", value: "500" },
    { label: "Semi-bold", value: "600" },
    { label: "Bold", value: "700" },
  ],
};

export const FIELD_NAMES = [
  "enabled",
  "cartPosition",
  "backgroundColor",
  "iconColor",
  "buttonRadius",
  "width",
  "height",
  "quantityBackgroundColor",
  "quantityTextColor",
  "quantityBadgeWidth",
  "quantityBadgeHeight",
  "quantityBadgeRadius",
  "showQuantityBadge",
  "selectedIcon",
  "uploadedIconData",
  "uploadedIconType",
  "customIconWidth",
  "customIconHeight",
  "quantityBadgePosition",
  "priceBackgroundColor",
  "deviceVisibility",
  "enableHoverAnimation",
  "animationType",
  "showPricing",
  "pricingTextColor",
  "pricingFontSize",
  "pricingFontWeight",
  "customCSS",
  "structuredTopSectionBgColor",
  "structuredBottomSectionBgColor",
  "structuredItemsTextColor",
  "structuredPriceTextColor",
  "structuredCurrencySymbol",
];
