api_version = "2025-07"
type = "theme_app_extension"
name = "Sticky Cart Widget"
handle = "sticky-cart-widget"

[build]
command = ""
watch = []

[settings]
[[settings.groups]]
name = "Sticky Cart"
settings = []
